# Generated by Django 2.2.5 on 2019-10-30 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MasterBettingSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default='False', editable=False, max_length=10)),
                ('is_scored', models.BooleanField(default=False, editable=False)),
                ('title', models.CharField(default='Week of MM/DD-MM/DD', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_team', models.CharField(max_length=20, null=True, verbose_name='Favorite Team')),
                ('underdog_team', models.CharField(max_length=20, null=True, verbose_name='Underdog Team')),
                ('favorite_score', models.PositiveIntegerField(default=None, null=True)),
                ('betting_line', models.PositiveIntegerField(default=None, null=True)),
                ('underdog_score', models.PositiveIntegerField(default=None, null=True)),
                ('network_name', models.CharField(max_length=10, null=True)),
                ('date_time', models.DateTimeField(null=True)),
                ('betting_sheet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BettingSheets.MasterBettingSheet', verbose_name='Master Betting Sheet')),
            ],
        ),
    ]
