# Generated by Django 2.2.5 on 2019-10-30 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BettingSheets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_of_the_week',
            field=models.BooleanField(default=False),
        ),
    ]
