# Generated by Django 2.2.5 on 2019-10-21 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BettingSheets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='betting_line',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='game',
            name='date_time',
            field=models.TextField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='network_name',
            field=models.TextField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='team1',
            field=models.TextField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='team2',
            field=models.TextField(max_length=4, null=True),
        ),
    ]
