# Generated by Django 2.2.5 on 2019-10-22 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BettingSheets', '0002_auto_20191021_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterbettingsheet',
            name='title',
            field=models.TextField(default='Week of MM/DD-MM/DD'),
        ),
    ]
